# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: MySQL | Stop MySQL when resizing InnoDB log files.
  become: yes
  service:
    name: '{{ mysql_service_name }}'
    state: stopped
  when: mysql_installed.stat.exists == false or mysql_resize_innodb_log_files

- name: MySQL | Delete InnoDB log files when resizing.
  become: yes
  file:
    path: /var/lib/mysql/ib_logfile[01]
    state: absent
  when: mysql_installed.stat.exists == false or mysql_resize_innodb_log_files

- name: MySQL | Replace the global config file.
  become: yes
  template:
    src: '{{ mysql_global_config_template }}'
    dest: '{{ mysql_global_config_file }}'
    force: '{{ "yes" if mysql_installed.stat.exists == false or mysql_global_config_file_refresh else "no" }}'
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
  when: mysql_global_config_template | default(None) != None

- name: MySQL | Configure properties in global config file.
  become: yes
  ini_file:
    dest: '{{ mysql_global_config_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option | default(omit) }}'
    value: '{{ item.value | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
  with_items: '{{ mysql_global_config }}'
  when: mysql_global_config

- name: MySQL | Set ownership of directories.
  become: yes
  file:
    path: '{{ item }}'
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
  with_items:
    - '{{ mysql_pid_path }}'
    - '{{ mysql_log_path }}'
  when: ansible_os_family == 'RedHat'

- name: MySQL | Ensure MySQL is started.
  become: yes
  service:
    name: '{{ mysql_service_name }}'
    state: started

- name: MySQL | Prevent root login remotely.
  become: yes
  command: mysql -NBe 'DELETE FROM mysql.user WHERE User="root" AND Host NOT IN ("localhost", "127.0.0.1", "::1")'
  changed_when: false

- name: MySQL | Update the root user password.
  become: yes
  mysql_user:
    name: root
    host_all: yes
    password: '{{ mysql_root_password }}'
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_old_root_password }}'
  when: mysql_old_root_password | default(None) != None

- name: MySQL | Update the root config file with credentials.
  become: yes
  template:
    src: '{{ mysql_root_config_template }}'
    dest: '{{ mysql_root_config_file }}'
    owner: root
    group: root
    mode: 0600

- name: MySQL | Remove anonymous users.
  become: yes
  mysql_user:
    name: ''
    host_all: yes
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
    state: absent

- name: MySQL | Remove the test database.
  become: yes
  mysql_db:
    name: test
    state: absent

- name: MySQL | Configure users.
  become: yes
  mysql_user:
    append_privs: '{{ item.append_privs | default(omit) }}'
    check_implicit_admin: '{{ item.check_implicit_admin | default(omit) }}'
    config_file: '{{ item.config_file | default(omit) }}'
    connect_timeout: '{{ item.connect_timeout | default(omit) }}'
    encrypted: '{{ item.encrypted | default(omit) }}'
    host: '{{ item.host | default(omit) }}'
    host_all: '{{ item.host_all | default(omit) }}'
    login_host: '{{ item.login_host | default(omit) }}'
    login_password: '{{ item.login_password | default(omit) }}'
    login_port: '{{ item.login_port | default(omit) }}'
    login_unix_socket: '{{ item.login_unix_socket | default(omit) }}'
    login_user: '{{ item.login_user | default(omit) }}'
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    priv: '{{ item.priv | default("*.*:USAGE") }}'
    sql_log_bin: '{{ item.sql_log_bin | default(omit) }}'
    ssl_ca: '{{ item.ssl_ca | default(omit) }}'
    ssl_cert: '{{ item.ssl_cert | default(omit) }}'
    ssl_key: '{{ item.ssl_key | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    update_password: '{{ item.update_password | default(omit) }}'
  with_items: '{{ mysql_users }}'
  when: mysql_users

- name: MySQL | Configure databases.
  become: yes
  mysql_db:
    collation: '{{ item.collation | default("utf8_general_ci") }}'
    config_file: '{{ item.config_file | default(omit) }}'
    connect_timeout: '{{ item.connect_timeout | default(omit) }}'
    encoding: '{{ item.encoding | default("utf8") }}'
    login_host: '{{ item.login_host | default(omit) }}'
    login_password: '{{ item.login_password | default(omit) }}'
    login_port: '{{ item.login_port | default(omit) }}'
    login_unix_socket: '{{ item.login_unix_socket | default(omit) }}'
    login_user: '{{ item.login_user | default(omit) }}'
    name: '{{ item.name }}'
    quick: '{{ item.quick | default(omit) }}'
    single_transaction: '{{ item.single_transaction | default(omit) }}'
    ssl_ca: '{{ item.ssl_ca | default(omit) }}'
    ssl_cert: '{{ item.ssl_cert | default(omit) }}'
    ssl_key: '{{ item.ssl_key | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    target: '{{ item.target | default(omit) }}'
  with_items: '{{ mysql_databases }}'
  when: mysql_databases